export const IPC_CHANNELS = {
  DISPATCH: 'cmux:dispatch',
  QUERY_STATE: 'cmux:query-state',
  GET_INITIAL_STATE: 'cmux:get-initial-state',
  STATE_UPDATE: 'cmux:state-update',
  WINDOW_ID: 'cmux:window-id',
  PTY_WRITE: 'pty:write',
  PTY_METADATA: 'pty:metadata',
  PTY_SPAWN: 'pty:spawn',
  PTY_RESIZE: 'pty:resize',
  PTY_KILL: 'pty:kill',
  PTY_HAS: 'pty:has',
  PTY_DATA: 'pty:data',
  PTY_EXIT: 'pty:exit',
  PTY_GET_SHELLS: 'pty:get-shells',
  SHORTCUT: 'cmux:shortcut',
  SCROLLBACK_SAVE: 'cmux:scrollback-save',
  SCROLLBACK_LOAD: 'cmux:scrollback-load',
  BROWSER_EXECUTE: 'cmux:browser-execute',
  BROWSER_EXECUTE_RESULT: 'cmux:browser-execute-result',
  FILE_READ: 'cmux:file-read',
  FILE_LIST_DIR: 'cmux:file-list-dir',
  FILE_WATCH: 'cmux:file-watch',
  FILE_UNWATCH: 'cmux:file-unwatch',
  FILE_CHANGED: 'cmux:file-changed',
  DIALOG_OPEN_FOLDER: 'cmux:dialog-open-folder',
} as const;
